modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/tweaked-programs/cccbridge/issues/"

[[mods]]
modId="cccbridge"
version="1.5.0"
displayName="CC:C Bridge"
updateJSONURL=""
displayURL="https://tweaked-programs.cc/"
logoFile= "icon.png"
credits="Thanks for this mod goes out to agnor99, who understands modding much better!"
authors="Sammy L. Koch & Luke A. Hanssen"
description='''This mod adds compatibility between the ComputerCraft and Create mod!

Copyright 2023 Sammy L. Koch'''

[[dependencies.cccbridge]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE" # NONE; BEFORE; AFTER
    side="BOTH"
[[dependencies.cccbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cccbridge]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.b,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cccbridge]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.101.2,)"
    ordering="NONE"
    side="BOTH"
