modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/tweaked-programs/cccbridge/issues/"

[[mods]]
modId="cccbridge"
version="1.3.0"
displayName="CC:C Bridge"
updateJSONURL=""
displayURL="https://tweaked-programs.cc/tag/cccbridge/"
logoFile="icon.png"
credits="Thanks for this mod goes out to agnor99, who understands forge way better than me!!"
authors="Sammy L. Koch & Luke A. Hanssen"
description='''Adds compatibility between the ComputerCraft and Create mod!

Copyright 20222 Sammy L. Koch'''

[[dependencies.cccbridge]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE" # NONE; BEFORE; AFTER
    side="BOTH"
[[dependencies.cccbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cccbridge]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0c,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cccbridge]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.100.4,)"
    ordering="NONE"
    side="BOTH"
